spring:
   datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Drinkers?autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Jh742511
   servlet:
    multipart:
      file-size-threshold: 1MB
      max-file-size: 100MB
      max-request-size: 100MB
    
server: 
  port: 8888
  servlet: 
    session: 
      timeout: 6000s       
    context-path: /drinkers
  error: 
    whitelabel: 
      enabled: false
    include-stacktrace: always
